<?php
// Version: 2.1 Beta 4; Editor
global $editortxt;

$editortxt['Bold'] = 'Жирный';
$editortxt['Italic'] = 'Наклонный';
$editortxt['Underline'] = 'Подчеркнутый';
$editortxt['Strikethrough'] = 'Перечеркнутый';
$editortxt['Subscript'] = 'Индекс';
$editortxt['Superscript'] = 'Верхний индекс';
$editortxt['Align left'] = 'Выравнивание влево';
$editortxt['Center'] = 'По центру';
$editortxt['Align right'] = 'Выравнивание вправо';
$editortxt['Justify'] = 'Выравнивание';
$editortxt['Font Name'] = 'Шрифт';
$editortxt['Font Size'] = 'Размер шрифта';
$editortxt['Font Color'] = 'Цвет шрифта';
$editortxt['Remove Formatting'] = 'Очистить форматирование';
$editortxt['Cut'] = 'Вырезать';
$editortxt['Your browser does not allow the cut command. Please use the keyboard shortcut Ctrl/Cmd-X'] = 'Ваш браузер не поддерживает функцию вырезания. Используйте комбинацию Ctrl/Cmd-X';
$editortxt['Copy'] = 'Скопировать';
$editortxt['Your browser does not allow the copy command. Please use the keyboard shortcut Ctrl/Cmd-C'] = 'Ваш браузер не поддерживает функцию копирования. Используйте комбинацию Ctrl/Cmd-C';
$editortxt['Paste'] = 'Вставить';
$editortxt['Your browser does not allow the paste command. Please use the keyboard shortcut Ctrl/Cmd-V'] = 'Ваш браузер не поддерживает функцию вставки. Используйте комбинацию Ctrl/Cmd-V';
$editortxt['Paste your text inside the following box:'] = 'Вставьте текст в поле ввода:';
$editortxt['Paste Text'] = 'Вставить текст';
$editortxt['Bullet list'] = 'Маркированный список';
$editortxt['Numbered list'] = 'Нумерованный список';
$editortxt['Undo'] = 'Отменить';
$editortxt['Redo'] = 'Повторить';
$editortxt['Rows:'] = 'Строк:';
$editortxt['Cols:'] = 'Колонок:';
$editortxt['Insert a table'] = 'Вставить таблицу';
$editortxt['Insert a horizontal rule'] = 'Вставить горизонтальную линию';
$editortxt['Code'] = 'Код';
$editortxt['Insert a Quote'] = 'Вставить цитату';
$editortxt['Width (optional):'] = 'Ширина (опционально):';
$editortxt['Height (optional):'] = 'Высота (опционально):';
$editortxt['Insert an image'] = 'Вставить изображение';
$editortxt['E-mail:'] = 'E-mail: ';
$editortxt['Insert an email'] = 'Вставить адрес электронной почты';
$editortxt['URL:'] = 'Ссылка (URL): ';
$editortxt['Insert a link'] = 'Вставить ссылку';
$editortxt['Unlink'] = 'Убрать сылку';
$editortxt['More'] = 'Еще';
$editortxt['Insert an emoticon'] = 'Вставить смайл';
$editortxt['Video URL:'] = 'Ссылка на видео:';
$editortxt['Insert'] = 'Вставить ';
$editortxt['Insert a YouTube video'] = 'Вставить видео с YouTube';
$editortxt['Insert current date'] = 'Вставить текущую дату';
$editortxt['Insert current time'] = 'Вставить текущее время';
$editortxt['Print'] = 'Печать';
$editortxt['Preformatted Text'] = 'Отформатированный текст';
$editortxt['View source'] = 'Показать источник без HTML форматирования';
$editortxt['Pre'] = 'Отформатированный текст';
$editortxt['flash'] = 'Вставить Flash';
$editortxt['Float left'] = 'Плавающий блок слева';
$editortxt['Float right'] = 'Плавающий блок справа';
$editortxt['Maximize'] = 'Развернуть на весь экран';

?>